### ISSUE TITLE
[Feature] 配置文件增加对环境变量占位符的替换功能

### ISSUE THREAD

**Issue by ymh199478** [go-kratos/kratos#1065]
## 背景和动机

我们不希望将一些敏感的内容提交到 git 仓库中，所以这些敏感内容我们会和提交到 git 仓库的配置文件分离。

我们将这些机密内容放在 `dotenv运行时加载到环境变量`  或是 `直接存于环境变量` 中。

除此之外，配置可能因为程序运行环境发生改变，而需要动态的进行配置。

所以我们希望 kratos 能够在配置文件中动态的识别环境变量占位符，并使用环境变量值替换配置的内容。

## 提议的方案

> 修订1：提议方案需根据 @tonybase  [描述建议](https://github.com/go-kratos/kratos/issues/1065#issuecomment-865932445)修正
> 修订2：语义占位符采用 `os.Expand` 解析规则完成，废弃修订1的讨论

提案在配置文件中，通过占位符来替换环境变量中的功能:

提案建议的占位符风格有如下几种：

- `%(VARIABLE_NAME)`  ：传统的环境变量占位符
- `%env(VARIABLE_NAME)%` ： 带有环境变量处理器的占位符

#### 转义字符

双倍的 `%%` 将会被视作转义，从而豁免 `%` 占位符被解析

### 传统的环境变量占位符

传统的占位符替换机制只能够替换环境变量（包含 dotenv 运行时加载）的内容，占位符采用 `%()` 包装变量名：

```
data:
  database:
    driver: mysql
    source: %(DB_USERNAME):%(DB_PASSWORD)@tcp(127.0.0.1:3306)/test
```

### 带有环境变量处理器的占位符

环境变量处理器可以使配置程序具备更高的可扩展性，但相对会引入更高的复杂度。环境变量处理器实现可以被动态扩展。

占位符结构中 process 可形成管道:

```
%env([process:]VARIABLE_NAME)%
%env([process-a:][process-b:]VARIABLE_NAME)%
```

### 默认的处理器

提案中提议了一些默认的处理器方案，除了默认方案外，处理器方案可自由扩展(kratos 提出一种接口规范，使开发者可以扩展处理器)：

#### 读取环境变量

等价于传统的环境变量占位符：

```
data:
  database:
    user: %env(DB_USERNAME)%  # 等价于 %(DB_USERNAME)
```

#### 从文件读取内容的处理程序

从环境变量 `AUTH_FILE` 的值中获取文件存储路径，并读取该文件内容作为值

```
parameters:
    secrets: %env(file:AUTH_FILE)%
```

#### 支持 fallback 的环境变量读取

当指定环境变量读取失败时，可以使用默认环境变量的值替代

```
parameters:
    # 环境变量 PRIVATE_KEY 不存在，则使用 raw_key 值（非环境变量解析）替代
    private_key_a: %env(default:raw_key:PRIVATE_KEY)%

    # 环境变量 PRIVATE_KEY 不是一个有效的文件路径，使用 raw_key 值（非环境变量解析）替代
    private_key_b: %env(default:raw_key:file:PRIVATE_KEY)%
```

## 补充

- yaml 标准本身不支持变量占位符
- 占位符格式应在不同配置格式中都具备良好的可读性

**Comment by ymh199478** [comment]
我还在设想，这些配置的动态变量来源，可能不仅限于环境变量，kratos 程序本身也可能提供一些固定的变量，例如：

- 可以获取程序启动所在路径

```
parameters:
   foo: %app(app_dir)%/bar
```

这可以让人在配置时明确的知晓配置内容文件所在的路径，并且可以规范这些初始路径

**Comment by webliupeng** [comment]
自己实现一个decoder就行了。
```go
func ReplaceEnv(configData []byte) []byte {
	r, _ := regexp.Compile("\\${(.+)}")

	for _, match := range r.FindAllSubmatch(configData, -1) {
		key := os.Getenv(string(match[1]))
		if key != "" {
			configData = bytes.Replace(configData, match[0], []byte(key), 1)
		}
	}

	return configData
}


c := config.New(
	config.WithSource(
		file.NewSource(flagconf),
	),
	config.WithDecoder(func(kv *config.KeyValue, v map[string]interface{}) error {
		configData := ReplaceEnv(kv.Value)
		return yaml.Unmarshal(configData, v)
	}),
)
```

**Comment by ymh199478** [comment]
@webliupeng  实现 decoder 可以暂时性的解决简单的替换需求。但对于基础框架来说配置文件对环境变量占位符的替换是一个非常有用的实用功能，所以我还是建议能够将此功能集成到 kratos 框架中。

此特性是一个向下兼容的新增特性，不会破坏旧的解析行为和用户使用方式，但可以换来更好的配置扩展性。

**Comment by tonybase** [comment]
占位符语义建议使用  golang template 方式处理，比如 {{ .Key }} 方式，可以通过标准库完成处理。

**Comment by ymh199478** [comment]
我赞同使用 template 的方案，直接使用 template 可以少做很多事情。不过使用 template 的话也会带来额外的灵活度（这些功能可能用不上）

**Comment by kagaya85** [comment]
Hi，请问我是否可以尝试实现一下这个feature？

**Comment by shenqidebaozi** [comment]
@kagaya85 欢迎提交PR

**Comment by ymh199478** [comment]
@kagaya85 提好PR，记得AT我下哈～我也帮忙review下

**Comment by shenqidebaozi** [comment]
@kagaya85 如果是配置中心应该不需要模板替换，直接取值就可以了。

**Comment by kagaya85** [comment]
由于xml语法的问题，decoder不支持将xml反序列化到`map[string]interface{}`，所以现阶段应该无法支持xml格式的模板配置文件

另一方面，对于设置环境变量应该提供默认值的选择，这里有两种方案，不知道社区希望实现哪一种：

1. 默认值作为可选的第二个参数
```yaml
http:
  server: 
    port: {{ env "PORT" 8080 }}
```

2. 默认值作为环境变量字符的一部分
```yaml
http:
  server: 
    port: {{ env "$PORT:8080" }}
```

我比较倾向于后者，因为这更类似spring等配置环境变量的方式
