### ISSUE TITLE
tool/bmgen: 支持yaml定义router和auth信息

### ISSUE THREAD

**Issue by Terry-Mao** [go-kratos/kratos#111]
# 背景

我们希望在api.proto里面，描述出HTTP框架使用哪些Middleware，但是如果放在api.proto里，很尴尬，因为这个文件是暴露给客户端、服务端都使用的，扩展过于复杂的插件注入不是非常合适。而在HTTP框架中硬编码描述，会导致需要人肉书写Location，或者客户端不清楚注入了什么样的Auth方式。因此考虑使用yaml方式来扩展proto：

api.proto:

```protobuf
service Demo {
	rpc SayHello (HelloReq) returns (.google.protobuf.Empty);
	rpc SayHelloURL(HelloReq) returns (HelloResp) {
        option (google.api.http) = {
            get:"/kratos-demo/say_hello"
        };
    };
}
```
api.yaml instead of:

```yaml
type: bilibili.api.Demo
config_version: 1
name: demo.service.v1
title: Kratos Demo API

http:
  rules:
  - selector: 'demo.service.v1.Demo.SayHelloURL'
    get: '/kratos-demo/say_hello'
    additional_bindings:
    - get: '/demo.service.v1.Demo/SayHelloURL'
authentication:
  providers:
  - id: identify-service
  rules:
  - selector: 'demo.service.v1.Demo.SayHelloURL' # may be '*'
    oauth:
      canonical_scopes: |-
        auth,
        verify
```
**参考：**

- https://github.com/googleapis/googleapis/blob/master/google/pubsub/pubsub.yaml

- https://cloud.google.com/service-infrastructure/docs/service-management/reference/rpc/google.api
