### ISSUE TITLE
当conf.proto定义array时，从yaml配置文件解析成proto.Message时会解析失败

### ISSUE THREAD

**Issue by FFcjs** [go-kratos/kratos#1290]
#### What happened:
当conf.proto定义array时，从yaml配置文件解析成proto.Message时会解析失败
#### What you expected to happen:
解析成功
#### How to reproduce it (as minimally and precisely as possible):
conf.proto文件
```protobuffer
syntax = "proto3";
package athena.conf;

option go_package = "Athena/internal/conf;conf";

import "google/protobuf/duration.proto";
import "google/protobuf/any.proto";

message Bootstrap {
  Trace trace = 1;
  Tasks tasks =2;
  Data data = 3;
}

message Trace {
  string endpoint = 1;
}

message Tasks{
  message Task{
    string jobFun = 1;
    repeated google.protobuf.Any params = 2;
    repeated string tags = 3;
    bool singletonMode =4;
    int32  limitRunsTo =5;
    string cron =6;
  }
  repeated Task tasks =1;
}

message Data {
  message Database {
    string driver = 1;
    string source = 2;
    bool migrate =3;
  }
  message Redis {
    string network = 1;
    string addr = 2;
    string password = 3;
    int32 db = 4;
    google.protobuf.Duration dial_timeout = 5;
    google.protobuf.Duration read_timeout = 6;
    google.protobuf.Duration write_timeout = 7;
  }
  message Influxdb{
    string serverUrl = 1;
    string token = 2;
  }
  Database database = 1;
  Redis redis = 2;
  Influxdb influxdb = 3;
}

message Registry {
  message Consul {
    string address = 1;
    string scheme = 2;
  }
  Consul consul = 1;
}
```

解析代码：
```go
c := config.New(
config.WithSource(
	file.NewSource(flagconf),
),
)
if err := c.Load(); err != nil {
panic(err)
}

var bc conf.Bootstrap
if err := c.Scan(&bc); err != nil {
panic(err)
}
```

配置文件：
```yaml
tasks:
  -
    jobFun: DeviceDiscoveryTask
    tags:
      - DeviceDiscoveryTask
    singletonMode: true
    limitRunsTo: 1
    cron: 0/5 * * * * ? *
  -
    jobFun: DeviceDiscoveryTask2
    tags:
      - DeviceDiscoveryTask2
    singletonMode: true
    limitRunsTo: 1
    cron: 0/5 * * * * ? *
```

报错信息：
```
panic: proto: syntax error (line 1:460): unexpected token [
```

#### Environment:
- Kratos version (use `kratos -v`):kratos version v2.0.3
- Go version (use `go version`):go version go1.16.3 darwin/amd64
- OS (e.g: `cat /etc/os-release`): macOS
- Others:

**Comment by zwhyb** [comment]
```yaml
tasks:
  tasks:
    -
      jobFun: DeviceDiscoveryTask
      tags:
        - DeviceDiscoveryTask
      singletonMode: true
      limitRunsTo: 1
      cron: 0/5 * * * * ? *
    -
      jobFun: DeviceDiscoveryTask2
      tags:
        - DeviceDiscoveryTask2
      singletonMode: true
      limitRunsTo: 1
      cron: 0/5 * * * * ? *

```
你多套了一层 自己好好看看0.0
