### ISSUE TITLE
Non-string type config with default value can't work

### ISSUE THREAD

**Issue by jeffcaiz** [go-kratos/kratos#1565]
#### What happened:
It seems there is no way to apply default value to non-string type of config variable. It will always consider as a string and complain about wrong type like below.

> panic: proto: (line 1:20): invalid value for bool type: "true"

#### What you expected to happen:
For `booltype:   ${SOME_VAR:true}`,  it should works. If I say 'true' and it will be consider a boolean true, not panic with wrong type

#### How to reproduce it (as minimally and precisely as possible):
1. kratos v2.1.0 installed
2. kratos new showbug
3. Replace `conf.proto` with attached
4. Replace `config.yaml` with attached
5. make config
6. make build
7. ./bin/showbug -conf ./configs/config.yaml

#### Environment:
- Kratos version (use `kratos -v`): v2.1.0
- Go version (use `go version`): v1.17.1 linux
- OS (e.g: `cat /etc/os-release`): WSL2 on Windows 10
- Others:

###### config.yaml

```yaml
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
booltype: "${SOME_VAR:true}"
```

###### conf.proto

```protobuf
syntax = "proto3";
package kratos.api;

option go_package = "showbug/internal/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Data data = 2;
  bool booltype = 3;
}

message Server {
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 1;
  GRPC grpc = 2;
}

message Data {
  message Database {
    string driver = 1;
    string source = 2;
  }
  message Redis {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration read_timeout = 3;
    google.protobuf.Duration write_timeout = 4;
  }
  Database database = 1;
  Redis redis = 2;
}
```
