### ISSUE TITLE
[Question]kubernetes/registry.go的discovery问题

### ISSUE THREAD

**Issue by guihouchang** [go-kratos/kratos#2203]
请问kubernetes/registry.go  (http|grpc).WithEndpoint要怎么写？ discovery://namespace/appname 这样子？还是 discovery:///appname 或者 直接是appname？ 有什么快速的办法验证吗

**Comment by rogerogers** [comment]
server跟client一样就好了，感觉最好加上namespace避免client获取到其他其他同名的项目的pod
我做了一个demo #https://github.com/go-kratos/examples/pull/19

**Comment by guihouchang** [comment]
> server跟client一样就好了，感觉最好加上namespace避免client获取到其他其他同名的项目的pod 我做了一个demo #[go-kratos/examples#19](https://github.com/go-kratos/examples/pull/19)

我现在遇到一个问题r.GetService能获取到服务节点，但是直接使用discovery:///service-name 拨号的时候就会超时。

**Comment by rogerogers** [comment]
yaml方便贴一下吗

**Comment by guihouchang** [comment]
> yaml方便贴一下吗

```
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: authorizer
    labels:
      app: authorizer
      system: test
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: authorizer
    template:
      metadata:
        name: authorizer
        namespace: default
        labels:
          app: authorizer
          system: test
      spec:
        serviceAccountName: default
        containers:
          - name: authorizer
            image: ${IMAGE}
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: '250m'
                memory: '512Mi'
            ports:
              - name: grpc
                containerPort: 4001
                protocol: TCP
              - name: http
                containerPort: 4000
                protocol: TCP
            readinessProbe:
              tcpSocket:
                port: 4001
              initialDelaySeconds: 10     # 延迟探测时间(秒)【 在k8s第一次探测前等待秒 】
              periodSeconds: 2            # 执行探测频率(秒) 【 每隔秒执行一次 】
              timeoutSeconds: 1           # 超时时间
              successThreshold: 1         # 健康阀值
              failureThreshold: 3         # 不健康阀值
            livenessProbe:
              tcpSocket:
                port: 4001
              initialDelaySeconds: 10     # 延迟探测时间(秒)【 在k8s第一次探测前等待秒 】
              periodSeconds: 2            # 执行探测频率(秒) 【 每隔秒执行一次 】
              timeoutSeconds: 1           # 超时时间
              successThreshold: 1         # 健康阀值
              failureThreshold: 3         # 不健康阀值
```

**Comment by rogerogers** [comment]
pod的yaml，注册信息在pod的注解里

**Comment by guihouchang** [comment]
你要的看的是Pod的labels对吧？
  ```
labels:
    app: member
    kratos-service-app: test-member
    kratos-service-id: member-57dddbf94-d6b66
    kratos-service-version: 1b91d9e
    pod-template-hash: 57dddbf94
    system: test
```
