### ISSUE TITLE
got: 'key not found' when key contains the char `.`

### ISSUE THREAD

**Issue by qshuai** [go-kratos/kratos#2382]
#### What happened:
return the error `key not found` when fetch configuration value

#### What you expected to happen:
get the configuration value in config file

#### How to reproduce it (as minimally and precisely as possible):
1. config as following:
```yaml
...
users:
  james.smith:
    country: American
    age: 18
```

2. fetch the config value in business code:
```go
c.Value("users.james.smith.country").String()  // got error: key not found
c.Value("users.james.smith.age").Int()               // got error: key not found
```

#### Anything else we need to know?:
enough as the abovfe

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.5.0
- Go version (use `go version`): go version go1.17.13 darwin/arm64
- OS (e.g: `cat /etc/os-release`): mac os 12.4
- Others:

**Comment by yzrzr** [comment]
```
users:
  james:
    smith:
      country: American
      age: 18
```
