### ISSUE TITLE
[Feature] Config update cascade for `Config.Watch()`

### ISSUE THREAD

**Issue by AaronJan** [go-kratos/kratos#2801]
### Feature-request

Let's say we have 2 config sources:

1. Remote config system, under `remote` key
2. Local config file, under `local` key

Then we merge them like this:

```go
c := config.New(config.WithSource(
    remote,
    file.NewSource(path),
))
```

The config will be:

```yaml
remote:
  somePassword: xxxxxxx

local:
  redis:
    password: ${remote.somePassword}
```

The remote config could be updated anytime, we have to monitor changes using `config.Watch()`.

In this example, we are using `local.redis.password` for Redis initialization, not `remote.somePassword`, but we can't watch `local.redis.password` because when a referenced config value gets updated won't trigger update for any other config that includes it, so we have to watch `remote.somePassword` for now. It's unintuitive.

### Proposal

I think we can build a Relation Map when we first loaded all configs, then using this map to do update cascade (must avoid loop), enable developers to watch any config key they want.

But this problem could be further complicated if the updated config values include another config key(s) which they don't have before, in that case, we may have to update our Relation Map first.

I could help with this if it's approved.

**Comment by shenqidebaozi** [comment]
sorry, I didn't understand your proposal, can you describe it in more detail

**Comment by AaronJan** [comment]
> sorry, I didn't understand your proposal, can you describe it in more detail

@shenqidebaozi Sure, let's discuss the problem first.

Let's say there are 2 config sources, remote and local, and we use remote config placeholders in a local config value. If we express these configs in YAML, it would be like this:

```yaml
remote:
  mysql:
    username: root
    password: 123456

local:
  mysqlDsn: "${remote.mysql.username}:${remote.mysql.password}@127.0.0.1:3306/db"
```

If we want to recreate MySQL client when `remote.mysql.username` or `remote.mysql.password` gets updated, we can do this:

```go
c.Watch("remote.mysql.username", func(key string, value config.Value) {
  // ...
})

c.Watch("remote.mysql.password", func(key string, value config.Value) {
  // ...
})
```

But not this (which is the most intuitive way):

```go
c.Watch("local.mysqlDsn", func(key string, value config.Value) {
  // ...
})
```

The goal is to support latter use case.

But it's not easy.

Theoretically, you can do this (haven't test it):

```yaml
remote:
  config1: 123
  config2: ${config1}
  config3: ${config2}
```

This is basically a directed diagram and could contain loops, so when update happens, we must avoid infinite loop.

And it gets trickier, because orphan placeholder may occurs, like `remote.config1` could be disappeared because a remote source update.
