### ISSUE TITLE
[Feature] Add kratos errors to buf remote plugin

### ISSUE THREAD

**Issue by Aiden2014** [go-kratos/kratos#3330]
Please see the FAQ in our main README.md before submitting your issue.

### What problem is the feature used to solve?

We hope to add kratos protoc-gen-go-errors to https://buf.build/plugins . In this case we can use errors by defining in buf.gen.yaml in remote instead of installing the plugin in the computer firstly.
   The format of buf.gen.yaml is following.
```yaml
version: v2
...
plugins:
  - remote: buf.build/kratos/errors
    out: ./
    opt: paths=source_relative
```

### Requirements description of the feature

The protoc-gen-go-errors plugin should be added to  https://buf.build/plugins . We should install buf, build a docker image prepare buf.plugin.yaml and push plugin to the BSR.
### References

[plugins-on-buf.build](https://buf.build/plugins)
[custom-plugins-on-buf.build](https://buf.build/docs/bsr/remote-plugins/custom-plugins)
