### ISSUE TITLE
使用consul做为服务注册与发现，如果consul设置了token后，注册正常的，但是获取的grpc的conn是无法连接的

### ISSUE THREAD

**Issue by yuangu** [go-kratos/kratos#3609]
consul的docker-compose.yml

```
version: '3.1'

services:

  consul:
    image: hashicorp/consul:1.19.2
    container_name: consul
    restart: always
    ports:
      - "8500:8500"  # Web UI 和 API 端口
    command: "consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data -config-dir=/consul/config"
    volumes:
      - $PWD/consul_config:/consul/config
      - $PWD/data/consul:/consul/data 
```

consul_config/acl.json
```
{
    "acl": {
      "enabled": true,
      "default_policy": "deny",
      "enable_token_persistence": true
    }
  }
```

 consul consul acl bootstrap 会得到一个

```
AccessorID:   xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
SecretID:     xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Description:  Bootstrap Token (Global Management)
Local:        false
Create Time:  2024-01-01 00:00:00 +0000 UTC
Policies:
   00000000-0000-0000-0000-000000000001 - global-management
```

config.yaml里添加一个token

```
registry:
  consul:
    address:  127.0.0.1:8500
    scheme: http
    token:  9c236236-d018-827b-724e-8f4b70401795 #上方的SecretID
```
  
修改注册发现的配置。
```
func NewRegistrar(conf *conf.Registry) registry.Registrar {
	c := consulAPI.DefaultConfig()
	c.Address = conf.Consul.Address
	c.Scheme = conf.Consul.Scheme
//这里添加了一个token
	if conf.Consul.Token != "" {
		c.Token = conf.Consul.Token
	}
	cli, err := consulAPI.NewClient(c)
	if err != nil {
		panic(err)
	}
	r := consul.New(cli, consul.WithHealthCheck(false))
	return r
}
```

注册是正常的，但是，通过以下获取的grpc的conn是无法连接的，去掉了token是正常的
grpc.DialInsecure(
		context.Background(),
		grpc.WithEndpoint("discovery:///"+name),
		grpc.WithDiscovery(router.Ds),
		grpc.WithTimeout(timeout),
		// 通过 grpc.WithFilter 注入路由 Filter
		grpc.WithNodeFilter(filter),
		grpc.WithMiddleware(
			mmd.Client(),
			metrics.Client(
				metrics.WithSeconds(router.Meter.MetricSeconds),
				metrics.WithRequests(router.Meter.MetricRequests),
			),
		),
	)
