### ISSUE TITLE
解析配置文件失败

### ISSUE THREAD

**Issue by Peanuttown** [go-kratos/kratos#876]
#### What happened:
解析配置文件失败
当 yaml 格式的配置文件中，包含 对象数组时, eg:
```
students:
 - name: "name1"
    age: 18
 - name: "name2"
    age: 19
```
Scan 方法会返回 json unsupported map[interface{}] interface{}
#### What you expected to happen:
解析成功

#### Environment:
- Kratos version (use `kratos -v`): v2.0.0-beta3
- Go version (use `go version`): 1.15.7
- OS (e.g: `cat /etc/os-release`): Ubuntu16.04
- Others:
